### ISSUE TITLE
spaced path problem

### ISSUE THREAD

**Issue by Ealireza** [hjmangalam/parsyncfp#6]
dear sir 
for example i want to send /home/ali reza/* to another server 

parsyncfp  --NP=20 --startdir='/home/ali reza' /   root@dest:/home/test/

it's not working any way
i tried ali\ reza 

how escape " " space char in path ?

**Comment by hjmangalam** [comment]
Thanks for the bug report, Ealireza.  There are 2problems here, the 1st is a real bug, now fixed in the most recent patch the second is how to phrase the command.


If you want to move '/home/ali reza', the command would be:
`parsyncfp --NP=20 --startdir='/home/' 'ali reza' / root@dest:/home/test/
`
or just cd to /home and use the command:
`cd /home; parsyncfp --NP=20 ali\ reza / root@dest:/home/test/
`
That should work.  Again, thanks for reporting the bug.
hjm
